"use client";
import { t, useTeachingLocale } from "@/components/teaching/teaching-i18n";

import { useEffect,useState } from "react";
import { teachingApi,jsonBody,type Access,type Account } from "./api";
export default function AccessEditor({account,ceiling,onClose}:{account:Account;ceiling:Access;onClose:()=>void}){
  useTeachingLocale();

  const [access,setAccess]=useState<Access|null>(null);const [error,setError]=useState("");const [busy,setBusy]=useState(false);
  useEffect(()=>{teachingApi<Access>(`/api/v1/teaching/access/${account.id}`).then(setAccess).catch(e=>setError(e.message));},[account.id]);
  async function save(){if(!access)return;setBusy(true);try{await teachingApi(`/api/v1/teaching/access/${account.id}`,jsonBody(access));onClose();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  const names:Record<string,string>={chat:t("Chat 教学"),quiz:t("Quiz 测试"),research:t("深入研究"),homework:t("作业上传与批改")};
  return <section className="mt-5 rounded-2xl border border-[var(--border)] bg-[var(--card)] p-5" aria-label={t("账户权限")}><div className="flex justify-between"><h3 className="font-semibold">{account.username} {t("· 可用范围")}</h3><button onClick={onClose}>{t("关闭")}</button></div>{error&&<p role="alert" className="mt-3 text-sm text-red-700">{error}</p>}{access?<><fieldset disabled={busy} className="mt-4 space-y-5"><div><legend className="mb-2 text-sm font-medium">{t("功能")}</legend>{ceiling.features.map(f=><label key={f} className="mb-2 flex items-center gap-3 text-sm"><input type="checkbox" checked={access.features.includes(f)} onChange={e=>setAccess({...access,features:e.target.checked?[...access.features,f]:access.features.filter(v=>v!==f)})}/>{names[f]||f}</label>)}</div><div><p className="mb-2 text-sm font-medium">{t("可使用的模型")}</p>{ceiling.models.map(m=><label key={m.profile_id+":"+m.model_id} className="mb-2 flex items-center gap-3 text-sm"><input type="checkbox" checked={access.models.some(v=>v.profile_id===m.profile_id&&v.model_id===m.model_id)} onChange={e=>setAccess({...access,models:e.target.checked?[...access.models,m]:access.models.filter(v=>v.profile_id!==m.profile_id||v.model_id!==m.model_id)})}/>{m.label||m.model_id}</label>)}</div><div><p className="mb-2 text-sm font-medium">{t("主库资料")}</p>{ceiling.knowledge_bases.length?ceiling.knowledge_bases.map(k=><label key={k} className="mb-2 flex items-center gap-3 text-sm"><input type="checkbox" checked={access.knowledge_bases.includes(k)} onChange={e=>setAccess({...access,knowledge_bases:e.target.checked?[...access.knowledge_bases,k]:access.knowledge_bases.filter(v=>v!==k)})}/>{k.split(":kb:").pop()}</label>):<p className="text-sm text-[var(--muted-foreground)]">{t("暂无已授权的主库资料。")}</p>}</div></fieldset><button disabled={busy} onClick={save} className="mt-5 rounded-xl bg-[var(--primary)] px-4 py-2 text-sm text-[var(--primary-foreground)]">{busy?t("正在保存…"):t("保存权限")}</button></>:!error&&<p role="status" className="mt-4">{t("正在读取权限…")}</p>}</section>;
}
