"use client";
import { t, useTeachingLocale } from "@/components/teaching/teaching-i18n";

import { useEffect,useState } from "react";
import { fetchAuthStatus } from "@/lib/auth";
import { teachingApi,jsonBody,type Account,type Access } from "./api";
import StudentCourses from "./StudentCourses";
import AccessEditor from "./AccessEditor";
export default function AccountManager({parent=false,standalone=false}:{parent?:boolean;standalone?:boolean}){
  useTeachingLocale();

  const [accounts,setAccounts]=useState<Account[]>([]);const [owner,setOwner]=useState("");const [ceiling,setCeiling]=useState<Access>({models:[],knowledge_bases:[],features:[]});
  const [username,setUsername]=useState("");const [password,setPassword]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(true);const [editing,setEditing]=useState<Account|null>(null);const [coursesFor,setCoursesFor]=useState<Account|null>(null);
  async function load(){setBusy(true);setError("");try{const status=await fetchAuthStatus();setOwner(status?.user_id||"");if(parent){const data=await teachingApi<{students:Account[]}>("/api/v1/teaching/students");setAccounts(data.students);const catalog=await teachingApi<{models:Access["models"];knowledge_bases:Array<{id:string}>;features:string[]}>("/api/v1/teaching/catalog");setCeiling({models:catalog.models,knowledge_bases:catalog.knowledge_bases.map(k=>k.id),features:catalog.features});}else{setAccounts(await teachingApi<Account[]>("/api/v1/auth/users"));const data=await teachingApi<{models:Access["models"];knowledge_bases:Array<{id:string}>;features:string[]}>("/api/v1/teaching/catalog");setCeiling({models:data.models,knowledge_bases:data.knowledge_bases.map(k=>k.id),features:data.features});}}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  useEffect(()=>{void load();},[parent]);
  async function create(){setBusy(true);setError("");try{await teachingApi("/api/v1/auth/users",{...jsonBody({username,password,role:parent?"student":"parent"}),method:"POST"});setUsername("");setPassword("");await load();}catch(e){setError((e as Error).message);setBusy(false);}}
  async function toggle(account:Account){setBusy(true);setError("");try{await teachingApi(`/api/v1/auth/users/${encodeURIComponent(account.username)}/teaching`,jsonBody({role:account.role,parent_id:parent?owner:null,disabled:!account.disabled}));await load();}catch(e){setError((e as Error).message);setBusy(false);}}
  const manageable=accounts.filter(a=>a.role===(parent?"student":"parent"));const students=accounts.filter(a=>a.role==="student");
  return <section>{standalone?<h1 className="text-3xl font-semibold tracking-tight">{parent?t("学生账号"):t("家长账号")}</h1>:<h2 className="text-xl font-semibold">{parent?t("学生账号"):t("家长账号")}</h2>}<p className="mt-2 text-sm leading-6 text-[var(--muted-foreground)]">{parent?t("已使用 {{value0}} / 5 个名额。每个孩子拥有独立的学习记录。",{value0:manageable.length}):t("管理员分配家长的权限上限；学生账号由各自家长管理。")}</p>{error&&<p role="alert" className="mt-4 text-sm text-red-700">{error}</p>}
    <form onSubmit={e=>{e.preventDefault();void create();}} className="mt-5 grid gap-3 rounded-2xl bg-[var(--secondary)] p-5 md:grid-cols-[1fr_1fr_auto]"><label className="text-sm">{parent?t("学生用户名"):t("家长用户名")}<input required minLength={3} value={username} onChange={e=>setUsername(e.target.value)} autoComplete="off" className="mt-2 w-full border p-3"/></label><label className="text-sm">{t("初始密码")}<input type="password" required minLength={8} value={password} onChange={e=>setPassword(e.target.value)} autoComplete="new-password" className="mt-2 w-full border p-3"/></label><button disabled={busy||(parent&&manageable.length>=5)} className="self-end rounded-xl bg-[var(--primary)] px-5 py-3 text-sm text-[var(--primary-foreground)] disabled:opacity-50">{t("创建账号")}</button></form>
    <div className="mt-5 space-y-3">{manageable.map(a=><article key={a.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-[var(--border)] bg-[var(--card)] px-4 py-3"><div><p className="font-medium">{a.username}</p><p className="mt-1 text-xs text-[var(--muted-foreground)]">{a.disabled?t("已停用"):t("使用中")}</p></div><div className="flex flex-wrap gap-3">{parent&&<button onClick={()=>setCoursesFor(a)} className="rounded-lg border border-[var(--border)] px-3 py-2 text-sm">{t("学习课程")}</button>}<button onClick={()=>setEditing(a)} className="rounded-lg border border-[var(--border)] px-3 py-2 text-sm">{t("可用范围")}</button><button disabled={busy} onClick={()=>toggle(a)} className="px-3 py-2 text-sm underline">{a.disabled?t("启用"):t("停用")}</button></div></article>)}{!busy&&!manageable.length&&<p className="py-4 text-sm text-[var(--muted-foreground)]">{t("还没有账号。")}</p>}</div>
    {coursesFor&&<StudentCourses key={coursesFor.id} account={coursesFor} onClose={()=>setCoursesFor(null)}/>}
    {editing&&<AccessEditor account={editing} ceiling={ceiling} onClose={()=>setEditing(null)}/>}
    {!parent&&<section className="mt-10"><h2 className="text-lg font-semibold">{t("学生记录")}</h2><p className="mt-2 text-sm text-[var(--muted-foreground)]">{t("只供查看，配置由关联家长负责。")}</p><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-[var(--border)]"><th className="py-3">{t("学生")}</th><th>{t("关联家长")}</th><th>{t("状态")}</th></tr></thead><tbody>{students.map(s=><tr key={s.id} className="border-b border-[var(--border)]"><td className="py-3">{s.username}</td><td>{accounts.find(a=>a.id===s.parent_id)?.username||s.parent_id}</td><td>{s.disabled?t("已停用"):t("使用中")}</td></tr>)}</tbody></table></div></section>}
  </section>;
}
