"use client";
import { useEffect, useState } from "react";
import { teachingApi } from "./api";
import { t, useTeachingLocale } from "./teaching-i18n";
import MarkdownRenderer from "@/components/common/MarkdownRenderer";
type Evidence = {states:Array<{knowledge_node_id:string;title:string;status:string;policy_version:string;last_attempt_id:string|null;updated_at:string;due_at:string|null}>;attempts:Array<{id:string;prompt:string;response:string;submitted_at:string;judgments:Array<{id:string;verdict:string;rationale:string|null}>}>};
export default function LearningEvidence({studentId}:{studentId:string}){
 useTeachingLocale();
 const [data,setData]=useState<Evidence|null>(null);const [error,setError]=useState("");
 useEffect(()=>{let alive=true;setData(null);setError("");if(studentId)teachingApi<Evidence>(`/api/v1/teaching/students/${studentId}/evidence`).then(d=>{if(alive)setData(d);}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[studentId]);
 const states:Record<string,string>={new:t("尚无测试记录"),learning:t("正在学习"),mastered:t("测试证据支持掌握"),pending_recompute:t("学习状态正在重新计算")};
 return <section className="mt-8">{error&&<p role="alert" className="rounded-xl border border-[var(--border)] p-4 text-sm">{error}</p>}{data?<><h2 className="text-xl font-semibold">{t("学习证据与记忆")}</h2><p className="mt-3 text-sm leading-7 text-[var(--muted-foreground)]">{t("学习状态由作答与批改证据更新。展开后可查看原始作答及依据。")}</p>{!data.states.length&&<p className="mt-5 text-sm">{t("尚无测试记录")}</p>}<div className="mt-6 space-y-3">{data.states.map(state=><details key={state.knowledge_node_id} className="rounded-xl border border-[var(--border)] bg-[var(--card)] p-4"><summary className="cursor-pointer text-sm font-medium">{state.title}<span className="ml-3 font-normal text-[var(--muted-foreground)]">{states[state.status]||state.status}</span></summary><dl className="mt-4 grid gap-2 text-xs text-[var(--muted-foreground)]"><div>{t("更新于")} {new Date(state.updated_at).toLocaleString()}</div><div>{t("计算规则")} {state.policy_version}</div><div>{t("来源作答")} {state.last_attempt_id||"—"}</div></dl></details>)}</div><h3 className="mb-4 mt-8 font-semibold">{t("原始作答与批改记录")}</h3><div className="space-y-3">{data.attempts.map(a=><details key={a.id} className="rounded-xl border border-[var(--border)] p-4"><summary className="cursor-pointer text-sm">{a.prompt.slice(0,90)}</summary><div className="mt-4 space-y-4"><MarkdownRenderer content={a.prompt}/><div className="rounded-xl bg-[var(--secondary)] p-4"><p className="mb-2 text-xs">{t("你的作答")}</p><MarkdownRenderer content={a.response}/></div>{a.judgments.map(j=><div key={j.id} className="text-sm"><p>{t(j.verdict)}</p>{j.rationale&&<MarkdownRenderer content={j.rationale}/>}</div>)}<p className="text-xs text-[var(--muted-foreground)]">{new Date(a.submitted_at).toLocaleString()}</p></div></details>)}</div></>:!error&&studentId&&<p role="status">{t("正在读取…")}</p>}</section>;
}
