"use client";
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {education} from './education-api';
import {t,useTeachingLocale} from './teaching-i18n';
import MarkdownRenderer from '@/components/common/MarkdownRenderer';
type Task={set_id:string;learner_id:string;course_version_id:string};
type Paper={set_id:string;items:Array<{id:string;prompt:string;choices?:unknown;figure_url?:string}>;pending_submission?:boolean};
export default function LegacyAssessment({task,onComplete}:{task:Task;onComplete:()=>void}){
 useTeachingLocale();const [paper,setPaper]=useState<Paper|null>(null),[answers,setAnswers]=useState<Record<string,string>>({}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[result,setResult]=useState<{summary:{correct:number;answered:number};chat_handoff?:{href:string}}|null>(null);
 useEffect(()=>{education<Paper>(`set?learner_id=${encodeURIComponent(task.learner_id)}&course_version_id=${encodeURIComponent(task.course_version_id)}`,{method:'POST'}).then(d=>{if(d.set_id!==task.set_id)throw new Error(t('原练习状态已变化，请刷新。'));setPaper(d);}).catch(e=>setError(e.message));},[task]);
 async function submit(){if(!paper)return;setBusy(true);setError('');try{setResult(await education(paper.pending_submission?'set/recover':'set/submit',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...task,...(!paper.pending_submission?{answers:paper.items.map(i=>({item_id:i.id,response:answers[i.id]||''}))}:{})})}));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function leave(){setBusy(true);setError('');try{await education('set/skip',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(task)});onComplete();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="h-full overflow-auto"><main className="mx-auto max-w-3xl px-5 py-10"><h1 className="text-3xl font-semibold">Quiz</h1><p className="my-6 rounded-xl bg-[var(--secondary)] p-4 text-sm leading-7">{t('你有一份升级前的练习。先完成或放下它，再开始新版正式测试；已有记录会保留。')}</p>{error&&<p role="alert" className="mb-4 text-sm text-red-700">{error}</p>}{result?<><p className="text-sm">{t('已作答 {{value0}} 题，正确 {{value1}} 题。',{value0:result.summary.answered,value1:result.summary.correct})}</p>{result.chat_handoff&&<Link className="my-4 block underline" href={result.chat_handoff.href}>{t('在 Chat 查看讲解')}</Link>}<button onClick={onComplete} className="mt-4 border px-4 py-3">{t('返回 Quiz')}</button></>:paper&&<form onSubmit={e=>{e.preventDefault();void submit();}} className="space-y-6">{!paper.pending_submission&&paper.items.map((item,index)=><fieldset key={item.id} disabled={busy}><legend className="mb-3">{t('第 {{value0}} 题',{value0:index+1})}</legend><MarkdownRenderer content={item.prompt}/>{item.figure_url&&<img src={item.figure_url} alt={t('题目配图')} className="max-h-64 max-w-full"/>}{item.choices!=null&&<pre className="my-3 whitespace-pre-wrap text-sm">{typeof item.choices==='string'?item.choices:JSON.stringify(item.choices,null,2)}</pre>}<label className="mt-4 block text-sm">{t('你的作答')}<textarea rows={3} value={answers[item.id]||''} onChange={e=>setAnswers({...answers,[item.id]:e.target.value})} className="mt-2 w-full border p-3"/></label></fieldset>)}<div className="flex flex-wrap gap-3"><button disabled={busy} className="rounded-xl bg-[var(--primary)] px-5 py-3 text-sm text-[var(--primary-foreground)]">{paper.pending_submission?t('恢复结果'):t('提交全部作答')}</button>{!paper.pending_submission&&<button type="button" disabled={busy} onClick={leave} className="border px-5 py-3 text-sm">{t('放下这份旧练习')}</button>}</div></form>}</main></div>;
}
