"use client";
import { t, useTeachingLocale } from "@/components/teaching/teaching-i18n";

import {useEffect,useState} from "react";
import LearningEvidence from "@/components/teaching/LearningEvidence";
import AccountManager from "@/components/teaching/AccountManager";
import FamilyMaterials from "@/components/teaching/FamilyMaterials";
import {teachingApi,jsonBody,type Account} from "@/components/teaching/api";
import {education,type Person,type Course} from "@/components/teaching/education-api";
export default function ParentPage(){
  useTeachingLocale();

 const [tab,setTab]=useState("learning");const [students,setStudents]=useState<Account[]>([]);const [selected,setSelected]=useState("");const [goal,setGoal]=useState("");const [message,setMessage]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);const [progress,setProgress]=useState<Array<{title:string;status:string;score:number|null}>>([]);
 useEffect(()=>{teachingApi<{students:Account[]}>("/api/v1/teaching/students").then(d=>{setStudents(d.students);setSelected(d.students[0]?.id||"");setGoal(d.students[0]?.goal||"");}).catch(e=>setError(e.message));},[tab]);
 useEffect(()=>{let alive=true;setProgress([]);if(!selected)return;(async()=>{try{const people=await education<{people:Array<Person&{user_id?:string}>}>("people");const person=people.people.find(p=>p.user_id===selected);if(!person)return;const courses=await education<{courses:Course[]}>(`courses?learner_id=${encodeURIComponent(person.id)}`);const all=await Promise.all(courses.courses.map(c=>education<{nodes:Array<{title:string;status:string;score:number|null}>}>(`progress?learner_id=${encodeURIComponent(person.id)}&course_version_id=${encodeURIComponent(c.course_version_id)}`)));if(alive)setProgress(all.flatMap(d=>d.nodes));}catch(e){if(alive)setError((e as Error).message);}})();return()=>{alive=false;};},[selected]);
 async function save(){setBusy(true);setError("");setMessage("");try{await teachingApi(`/api/v1/teaching/students/${selected}/goal`,jsonBody({goal}));setStudents(s=>s.map(v=>v.id===selected?{...v,goal}:v));setMessage(t("学习目标已保存。"));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const labels:Record<string,string>={new:t("尚无测试记录"),learning:t("正在学习"),reviewing:t("需要复习"),mastered:t("测试证据支持掌握")};
 return <div className="h-full overflow-auto"><div className="mx-auto max-w-5xl px-5 py-8 md:px-10 md:py-12"><header><h1 className="text-3xl font-semibold tracking-tight">{t("陪伴孩子的每一步")}</h1><p className="mt-3 text-sm leading-7 text-[var(--muted-foreground)]">{t("了解进展，设定方向，把合适的资料交给导师。")}</p></header><nav aria-label={t("家长工作台")} className="my-8 flex flex-wrap gap-2">{[["learning",t("学习进展")],["accounts",t("学生账号")],["materials",t("家庭资料")]].map(([id,label])=><button key={id} aria-pressed={tab===id} onClick={()=>setTab(id)} className={`rounded-xl px-4 py-2 text-sm ${tab===id?"bg-[var(--primary)] text-[var(--primary-foreground)]":"border border-[var(--border)]"}`}>{label}</button>)}</nav>
 {tab==="accounts"?<AccountManager parent/>:tab==="materials"?<FamilyMaterials/>:<section>{error&&<p role="alert" className="mb-5 text-sm text-red-700">{error}</p>}{students.length?<><label htmlFor="parent-student" className="mb-2 block text-sm font-medium">{t("正在关注")}</label><select id="parent-student" value={selected} onChange={e=>{setSelected(e.target.value);setGoal(students.find(s=>s.id===e.target.value)?.goal||"");setMessage("");}} className="mb-7 w-full max-w-xs border p-3">{students.map(s=><option key={s.id} value={s.id}>{s.username}</option>)}</select><label htmlFor="learning-goal" className="mb-3 block text-lg font-semibold">{t("近期学习目标")}</label><textarea id="learning-goal" value={goal} onChange={e=>setGoal(e.target.value)} maxLength={4000} rows={4} placeholder={t("例如：理解分数之间的关系，能说明自己的解题思路。")} className="w-full border p-4"/><button onClick={save} disabled={busy} className="mt-3 rounded-xl bg-[var(--primary)] px-5 py-3 text-sm text-[var(--primary-foreground)]">{busy?t("正在保存…"):t("保存目标")}</button>{message&&<p role="status" className="mt-3 text-sm">{message}</p>}<h2 className="mb-4 mt-10 text-xl font-semibold">{t("学习记录")}</h2>{progress.length?<div className="space-y-3">{progress.map((p,i)=><div key={i} className="flex flex-wrap items-center justify-between gap-2 rounded-xl border border-[var(--border)] bg-[var(--card)] p-4"><span>{p.title}</span><span className="text-sm text-[var(--muted-foreground)]">{labels[p.status]||p.status}</span></div>)}</div>:<p className="text-sm text-[var(--muted-foreground)]">{t("尚无关联课程的测试证据。聊天不会被直接当作“已掌握”。")}</p>}<LearningEvidence studentId={selected}/></>:<div className="rounded-2xl bg-[var(--secondary)] p-7"><h2 className="text-xl font-semibold">{t("先为孩子准备一个账号")}</h2><p className="mt-3 text-sm leading-7">{t("每个孩子都有独立的对话和学习记录，你可以管理最多 5 个学生账号。")}</p><button onClick={()=>setTab("accounts")} className="mt-5 rounded-xl bg-[var(--primary)] px-5 py-3 text-sm text-[var(--primary-foreground)]">{t("创建学生账号")}</button></div>}</section>}
 </div></div>;
}
