"use client";
import { t, useTeachingLocale } from "@/components/teaching/teaching-i18n";

import {useEffect,useState} from "react";
import {teachingApi,jsonBody} from "@/components/teaching/api";
type Model={profile_id:string;model_id:string};
type Policy={teacher_model:Model|null;reasoning_model:Model|null;instructions:string;tools:string[];material_engine:string};
type Snapshot={policy:Policy;revision:number};
export default function TeachingPolicyPage(){
  useTeachingLocale();

 const [snapshot,setSnapshot]=useState<Snapshot|null>(null);const [models,setModels]=useState<Array<Model&{label:string}>>([]);const [error,setError]=useState("");const [saved,setSaved]=useState(false);const [busy,setBusy]=useState(false);
 async function load(){setError("");try{const [policy,catalog]=await Promise.all([teachingApi<Snapshot>("/api/v1/teaching/policy"),teachingApi<{models:Array<Model&{label:string}>}>("/api/v1/teaching/catalog")]);setSnapshot(policy);setModels(catalog.models);}catch(e){setError((e as Error).message);}}
 useEffect(()=>{void load();},[]);
 function update(patch:Partial<Policy>){if(snapshot){setSnapshot({...snapshot,policy:{...snapshot.policy,...patch}});setSaved(false);}}
 async function save(){if(!snapshot)return;setBusy(true);setError("");try{setSnapshot(await teachingApi<Snapshot>("/api/v1/teaching/policy",jsonBody(snapshot)));setSaved(true);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="h-full overflow-auto"><main className="mx-auto max-w-3xl px-6 py-10"><h1 className="text-3xl font-semibold">{t("导师如何教学")}</h1><p className="mt-4 text-sm leading-7 text-[var(--muted-foreground)]">{t("统一定义教学行为。实际调用模型仍受家长与学生的授权范围约束。")}</p>{error&&<div role="alert" className="mt-5 text-sm text-red-700">{error}<button onClick={load} className="ml-3 underline">{t("重新读取")}</button></div>}{snapshot?<form onSubmit={e=>{e.preventDefault();void save();}} className="mt-8 space-y-7"><fieldset disabled={busy} className="space-y-7">{(["teacher_model","reasoning_model"] as const).map(field=><label key={field} className="block text-sm font-medium">{field==="teacher_model"?t("日常教学模型"):t("深度推理模型")}<select required={field==="teacher_model"} value={snapshot.policy[field]?JSON.stringify(snapshot.policy[field]):""} onChange={e=>update({[field]:e.target.value?JSON.parse(e.target.value):null})} className="mt-3 w-full border p-3"><option value="">{field==="teacher_model"?t("请选择教学模型"):t("沿用日常教学模型")}</option>{models.map(m=><option key={m.profile_id+":"+m.model_id} value={JSON.stringify({profile_id:m.profile_id,model_id:m.model_id})}>{m.label}</option>)}</select></label>)}<label className="block text-sm font-medium">{t("导师职责与讲解方式")}<textarea rows={7} maxLength={8000} value={snapshot.policy.instructions} onChange={e=>update({instructions:e.target.value})} className="mt-3 w-full border p-4"/></label><fieldset><legend className="mb-3 text-sm font-medium">{t("可自动调用的能力")}</legend>{[["reason",t("深入推理")],["web_search",t("查找网络资料")],["paper_search",t("查找研究文献")]].map(([key,label])=><label key={key} className="my-3 flex items-center gap-3 text-sm"><input type="checkbox" checked={snapshot.policy.tools.includes(key)} onChange={e=>update({tools:e.target.checked?[...snapshot.policy.tools,key]:snapshot.policy.tools.filter(t=>t!==key)})}/>{label}</label>)}</fieldset><label className="block text-sm font-medium">{t("家庭资料的索引服务")}<select value={snapshot.policy.material_engine} onChange={e=>update({material_engine:e.target.value})} className="mt-3 w-full border p-3">{["llamaindex","lightrag","graphrag","pageindex"].map(v=><option key={v}>{v}</option>)}</select></label></fieldset><p className="rounded-xl bg-[var(--secondary)] p-4 text-sm leading-7">{t("Chat 只负责教学与讲解，Quiz 独立测试。以上教学策略不能更改这条产品边界。")}</p><button disabled={busy} className="rounded-xl bg-[var(--primary)] px-5 py-3 text-sm text-[var(--primary-foreground)]">{busy?t("正在保存…"):t("保存教学策略")}</button>{saved&&<p role="status" className="text-sm">{t("已保存，新的对话轮次将采用此策略。")}</p>}</form>:!error&&<p role="status" className="mt-8">{t("正在读取…")}</p>}</main></div>;
}
