"use client";
import { useEffect,useState } from 'react';
import Link from 'next/link';
import { education } from '@/components/teaching/education-api';
import { t,useTeachingLocale } from '@/components/teaching/teaching-i18n';
type Course={course_version_id:string;title:string;subject_key:string;curriculum_key:string|null;grade:number|null;competition_domain:string|null;units:string[];nodes:Array<{id:string;title:string}>};
type Item={id:string;prompt:string;status:string;reviewer:string|null;reviewed_at:string|null;unit_id:string|null;tier:string|null;bank:string|null;core:boolean|null;points:number|null;family_key:string|null};
const primary='rounded-xl bg-[var(--primary)] px-4 py-2.5 text-sm text-[var(--primary-foreground)] disabled:opacity-40';
function ItemEditor({item,course}:{item:Item;course:Course}){
 const [form,setForm]=useState({unit_id:item.unit_id||course.units[0]||'',tier:item.tier||'B',bank:item.bank||'regular',core:Boolean(item.core),points:item.points||5,family_key:item.family_key||item.id}),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function save(){setBusy(true);setMessage('');try{await education(`assessment-admin/items/${item.id}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});setMessage(t('已保存'));}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 return <details className="border-b border-[var(--border)] py-4"><summary className="cursor-pointer text-sm leading-7">{item.prompt.slice(0,120)} <span className="text-xs text-[var(--muted-foreground)]">{item.status==='production'&&item.reviewer&&item.reviewed_at?t('已审核题目'):t('待审核，不进入正式测试')}</span></summary><form onSubmit={e=>{e.preventDefault();void save();}} className="mt-4 space-y-4"><fieldset disabled={busy} className="grid gap-4 sm:grid-cols-2"><label className="text-sm">{t('对应单元')}<select className="mt-2 w-full border p-2" value={form.unit_id} onChange={e=>setForm({...form,unit_id:e.target.value})}>{course.nodes.filter(n=>course.units.includes(n.id)).map(n=><option key={n.id} value={n.id}>{n.title}</option>)}</select></label><label className="text-sm">{t('题库用途')}<select className="mt-2 w-full border p-2" value={form.bank} onChange={e=>setForm({...form,bank:e.target.value,...(e.target.value==='competition'?{tier:'A'}:{})})}><option value="regular">{t('常规考核')}</option>{course.competition_domain&&<option value="competition">{t('STEM竞赛')}</option>}</select></label><label className="text-sm">{t('难度')}<select className="mt-2 w-full border p-2" disabled={form.bank==='competition'} value={form.tier} onChange={e=>setForm({...form,tier:e.target.value})}><option value="A">{t('A · 难')}</option><option value="B">{t('B · 适中')}</option><option value="C">{t('C · 简单')}</option></select></label><label className="text-sm">{t('分值')}<input type="number" required min={1} max={100} className="mt-2 w-full border p-2" value={form.points} onChange={e=>setForm({...form,points:Number(e.target.value)})}/></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.core} onChange={e=>setForm({...form,core:e.target.checked})}/>{t('考察基础核心知识')}</label><label className="text-sm">{t('同题与变式组编号')}<input required className="mt-2 w-full border p-2" value={form.family_key} maxLength={160} onChange={e=>setForm({...form,family_key:e.target.value})}/></label></fieldset><p className="text-xs leading-6 text-[var(--muted-foreground)]">{t('同一道题的改写与数值变式必须使用同一组编号，避免重复抽取。')}</p><button className={primary} disabled={busy}>{t('保存题目分类')}</button>{message&&<p role="status" className="text-sm">{message}</p>}</form></details>;
}
export default function AssessmentAdmin(){
 useTeachingLocale();const [courses,setCourses]=useState<Course[]>([]),[selected,setSelected]=useState(''),[form,setForm]=useState<Course|null>(null),[items,setItems]=useState<Item[]>([]),[search,setSearch]=useState(''),[error,setError]=useState(''),[saved,setSaved]=useState(false),[busy,setBusy]=useState(false),[limit,setLimit]=useState(30);
 async function load(){const data=await education<{courses:Course[]}>('assessment-admin/courses');setCourses(data.courses);return data.courses;}
 useEffect(()=>{load().then(rows=>setSelected(rows[0]?.course_version_id||'')).catch(e=>setError(e.message));},[]);
 useEffect(()=>{let live=true;const course=courses.find(c=>c.course_version_id===selected);setForm(course?{...course,curriculum_key:course.curriculum_key||'',grade:course.grade||1}:null);setItems([]);setSaved(false);setError('');setLimit(30);setSearch('');if(course?.curriculum_key)education<{items:Item[]}>(`assessment-admin/courses/${selected}/items`).then(d=>{if(live)setItems(d.items);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[selected,courses]);
 async function save(){if(!form)return;setBusy(true);setError('');try{await education(`assessment-admin/courses/${selected}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({curriculum_key:form.curriculum_key,grade:form.grade,units:form.units,competition_domain:form.competition_domain})});await load();setSaved(true);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const filtered=items.filter(i=>(i.prompt+i.id).toLowerCase().includes(search.toLowerCase()));
 const domains:Record<string,string>={mathematics:t('数学'),science:t('科学'),technology:t('技术'),engineering:t('工程')};
 return <div className="h-full overflow-auto"><main className="mx-auto max-w-4xl px-5 py-9 md:px-10"><Link href="/admin/teaching" className="text-sm underline">{t('返回教学策略')}</Link><h1 className="mt-5 text-3xl font-semibold">{t('课程考核与题库')}</h1><p className="mt-4 text-sm leading-7 text-[var(--muted-foreground)]">{t('先定义课程范围，再分类已审核题目。竞赛仅用于 STEM，数学优先。题量不足时停止发卷，不自动降低难度。')}</p>{error&&<p role="alert" className="mt-4 text-sm text-red-700">{error}</p>}<label className="mt-7 block text-sm">{t('已发布课程')}<select value={selected} onChange={e=>setSelected(e.target.value)} className="mt-2 w-full border p-3">{courses.map(c=><option key={c.course_version_id} value={c.course_version_id}>{c.title} · {c.subject_key}</option>)}</select></label>{form&&<form className="mt-6 space-y-5" onSubmit={e=>{e.preventDefault();void save();}}><fieldset disabled={busy} className="grid gap-5 sm:grid-cols-2"><label className="text-sm">{t('课程体系编号')}<input required pattern="[a-zA-Z0-9_.-]+" maxLength={80} value={form.curriculum_key||''} onChange={e=>setForm({...form,curriculum_key:e.target.value})} className="mt-2 w-full border p-3"/></label><label className="text-sm">{t('本课程学习年级')}<input type="number" required min={1} max={12} value={form.grade||1} onChange={e=>setForm({...form,grade:Number(e.target.value)})} className="mt-2 w-full border p-3"/></label><label className="text-sm sm:col-span-2">{t('竞赛领域')}<select value={form.competition_domain||''} onChange={e=>setForm({...form,competition_domain:e.target.value||null})} className="mt-2 w-full border p-3"><option value="">{t('不开启竞赛')}</option>{Object.entries(domains).map(([key,name])=><option key={key} value={key}>{name}</option>)}</select></label><fieldset className="sm:col-span-2"><legend className="mb-3 text-sm">{t('必修单元与核心覆盖范围')}</legend><div className="grid gap-3 sm:grid-cols-2">{form.nodes.map(n=><label key={n.id} className="flex items-center gap-3 text-sm"><input type="checkbox" checked={form.units.includes(n.id)} onChange={e=>setForm({...form,units:e.target.checked?[...form.units,n.id]:form.units.filter(id=>id!==n.id)})}/>{n.title}</label>)}</div></fieldset></fieldset><p className="rounded-xl bg-[var(--secondary)] p-4 text-xs leading-6">{t('发出正式试卷后，课程考核范围锁定；变更请发布新版本。可继续补充未发出过的新题。')}</p><button disabled={busy||!form.units.length} className={primary}>{t('保存考核范围')}</button>{saved&&<p role="status" className="text-sm">{t('已保存')}</p>}</form>}{items.length>0&&form&&<section className="mt-10"><h2 className="text-xl font-semibold">{t('题目分类与去重')}</h2><label className="mt-4 block text-sm">{t('查找题目')}<input value={search} onChange={e=>{setSearch(e.target.value);setLimit(30);}} className="mt-2 w-full border p-3"/></label>{filtered.slice(0,limit).map(item=><ItemEditor key={item.id} item={item} course={form}/>)}{filtered.length>limit&&<button onClick={()=>setLimit(v=>v+30)} className="mt-4 border px-4 py-2">{t('查看更多')}</button>}</section>}</main></div>;
}
