"use client";
import { t, useTeachingLocale } from "@/components/teaching/teaching-i18n";

import { useEffect, useState } from "react";
import Link from "next/link";
import MarkdownRenderer from "@/components/common/MarkdownRenderer";
import { education, type Course, type Person } from "@/components/teaching/education-api";

type Item = {id:string; prompt:string; figure_url?:string; choices?:unknown};
type Paper = {set_id:string|null; items:Item[]; message?:string; pending_submission?:boolean};
type Result = {results:Array<{item_id:string;prompt:string;your_response:string;is_correct:boolean|null;correct_answer:string}>;summary:{answered:number;correct:number;awaiting_review:number};chat_handoff:{href:string}};
export default function QuizPage() {
  useTeachingLocale();

  const [learner,setLearner]=useState("");const [courses,setCourses]=useState<Course[]>([]);const [course,setCourse]=useState("");
  const [paper,setPaper]=useState<Paper|null>(null);const [answers,setAnswers]=useState<Record<string,string>>({});const [result,setResult]=useState<Result|null>(null);
  const [busy,setBusy]=useState(true);const [error,setError]=useState("");
  useEffect(()=>{let alive=true;(async()=>{try{const data=await education<{people:Person[];signed_in_profile_id:string}>("people");const id=data.signed_in_profile_id;if(!id) throw new Error(t("学习档案尚未关联，请联系家长。"));const list=await education<{courses:Course[]}>(`courses?learner_id=${encodeURIComponent(id)}`);if(alive){setLearner(id);setCourses(list.courses);setCourse(list.courses[0]?.course_version_id||"");}}catch(e){if(alive)setError((e as Error).message);}finally{if(alive)setBusy(false);}})();return()=>{alive=false;};},[]);
  async function issue() {setBusy(true);setError("");try{const next=await education<Paper>(`set?learner_id=${encodeURIComponent(learner)}&course_version_id=${encodeURIComponent(course)}`,{method:"POST"});setPaper(next);setAnswers({});setResult(null);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function submit(recover=false) {if(!paper?.set_id)return;setBusy(true);setError("");try{const data=await education<Result>(recover ? "set/recover" : "set/submit",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({learner_id:learner,course_version_id:course,set_id:paper.set_id,...(recover?{}:{answers:paper.items.map(i=>({item_id:i.id,response:answers[i.id]||""}))})})});setResult(data);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <div className="h-full overflow-y-auto"><div className="mx-auto max-w-3xl px-5 py-8 md:px-10 md:py-12"><header className="mb-9"><h1 className="text-3xl font-semibold tracking-tight">Quiz</h1><p className="mt-3 text-sm leading-7 text-[var(--muted-foreground)]">{t("独立完成测试，提交后查看答案。讲解与订正会自动进入 Chat。")}</p></header>
    {error&&<p role="alert" className="mb-5 rounded-lg border border-red-300 p-4 text-sm text-red-700">{error}</p>}
    {!paper && <section><label htmlFor="quiz-course" className="mb-2 block text-sm font-medium">{t("测试科目")}</label><select id="quiz-course" value={course} onChange={e=>setCourse(e.target.value)} disabled={busy} className="w-full rounded-lg border border-[var(--border)] bg-[var(--background)] p-3 text-sm">{courses.map(c=><option key={c.course_version_id} value={c.course_version_id}>{c.title}</option>)}</select>{!busy&&!courses.length&&<p className="mt-3 text-sm text-[var(--muted-foreground)]">{t("暂无可用测试，请联系家长设置学习目标。")}</p>}<button onClick={issue} disabled={busy||!course} className="mt-6 rounded-lg bg-[var(--primary)] px-5 py-3 text-sm text-[var(--primary-foreground)] disabled:opacity-40">{busy?t("正在准备…"):t("开始测试")}</button></section>}
    {paper&&!result&&<form onSubmit={e=>{e.preventDefault();void submit();}} className="space-y-8">{paper.message&&<p role="status">{paper.message}</p>}{paper.pending_submission?<div><p>{t("作答已保存，可以继续读取批改结果。")}</p><button type="button" disabled={busy} onClick={()=>submit(true)} className="mt-4 rounded-lg border p-3">{t("恢复结果")}</button></div>:paper.items.map((item,index)=><fieldset key={item.id} className="border-b border-[var(--border)] pb-8"><legend className="mb-3 text-sm font-medium">{t("第 {{value0}} 题",{value0:index+1})}</legend><MarkdownRenderer content={item.prompt}/>{item.figure_url&&<img src={item.figure_url} alt={t("题目配图")} className="my-4 max-h-72 max-w-full"/>}{item.choices!=null&&<div className="my-4 space-y-2">{typeof item.choices==="string"?<MarkdownRenderer content={item.choices}/>:Object.entries(item.choices as Record<string,string>).map(([key,value])=><p key={key} className="flex gap-3 rounded-xl bg-[var(--secondary)] px-4 py-3 text-sm"><span className="font-semibold">{key}</span><span>{String(value)}</span></p>)}</div>}<label htmlFor={`answer-${index}`} className="mb-2 mt-5 block text-sm">{t("你的作答")}</label><textarea id={`answer-${index}`} required disabled={busy} value={answers[item.id]||""} onChange={e=>setAnswers(v=>({...v,[item.id]:e.target.value}))} rows={3} className="w-full rounded-lg border border-[var(--border)] bg-[var(--background)] p-3 text-sm focus:outline-[var(--primary)]"/></fieldset>)}{paper.items.length>0&&!paper.pending_submission&&<button disabled={busy} className="rounded-lg bg-[var(--primary)] px-5 py-3 text-sm text-[var(--primary-foreground)] disabled:opacity-40">{busy?t("正在保存和批改…"):t("提交全部作答")}</button>}</form>}
    {result&&<section><h2 className="text-xl font-semibold">{t("测试结果")}</h2><p className="mt-3 text-sm">{t("已作答 {{value0}} 题，正确 {{value1}} 题。",{value0:result.summary.answered,value1:result.summary.correct})}{result.summary.awaiting_review>0?t(" {{value0}} 题等待复核。",{value0:result.summary.awaiting_review}):""}</p><div className="mt-6 space-y-6">{result.results.map((row,i)=><article key={row.item_id} className="border-b border-[var(--border)] pb-5"><h3 className="mb-2 font-medium">{t("第 {{value0}} 题",{value0:i+1})} · {row.is_correct===null?t("等待复核"):row.is_correct?t("正确"):t("需要订正")}</h3><MarkdownRenderer content={row.prompt}/><p className="mt-3 text-sm">{t("你的作答：")}{row.your_response}</p><p className="mt-2 text-sm">{t("参考答案：")}{row.correct_answer}</p></article>)}</div><p className="mt-6 text-sm text-[var(--muted-foreground)]">{t("讲解与原始作答已自动保存到 Chat。")}</p><Link href={result.chat_handoff.href} className="mt-4 inline-flex rounded-lg bg-[var(--primary)] px-5 py-3 text-sm text-[var(--primary-foreground)]">{t("在 Chat 查看讲解")}</Link><button onClick={()=>{setPaper(null);setResult(null);}} className="ml-4 mt-4 rounded-lg border border-[var(--border)] px-5 py-3 text-sm">{t("返回 Quiz")}</button></section>}
  </div></div>;
}
