"use client";
import { useCallback,useEffect,useRef,useState } from 'react';
import Link from 'next/link';
import LegacyAssessment from '@/components/teaching/LegacyAssessment';
import { Clock3,Check } from 'lucide-react';
import MarkdownRenderer from '@/components/common/MarkdownRenderer';
import { education } from '@/components/teaching/education-api';
import { t,useTeachingLocale } from '@/components/teaching/teaching-i18n';
import { modeNames,promotionText,foundationText,type FoundationFollowup,type AssessmentResult,type Exam } from '@/components/teaching/assessment-types';
type Course={course_version_id:string;title:string;grade:number;learning_grade:number|null;units:Array<{id:string;title:string}>;modes:string[];coverage:{missing_units:string[];missing_core:string[]}};
type Report={assessment:AssessmentResult;results:Array<{item_id:string;prompt:string;your_response:string;is_correct:boolean|null;correct_answer:string}>;chat_handoff?:{href:string}};
const primary='rounded-xl bg-[var(--primary)] px-5 py-3 text-sm text-[var(--primary-foreground)] disabled:opacity-40';
export default function QuizPage(){
 useTeachingLocale();const names=modeNames();
 const [learner,setLearner]=useState(''),[courses,setCourses]=useState<Course[]>([]),[course,setCourse]=useState(''),[mode,setMode]=useState('daily'),[unit,setUnit]=useState('');
 const [specs,setSpecs]=useState<Record<string,[number,number]>>({}),[paper,setPaper]=useState<Exam|null>(null),[answers,setAnswers]=useState<Record<string,string>>({}),[report,setReport]=useState<Report|null>(null);
 const [legacy,setLegacy]=useState<{set_id:string;learner_id:string;course_version_id:string}|null>(null);
 const [busy,setBusy]=useState(true),[error,setError]=useState(''),[sync,setSync]=useState('saved'),[remaining,setRemaining]=useState(0),[conflict,setConflict]=useState(false);
 const viewport=useRef<HTMLDivElement|null>(null);
 const paperRef=useRef<Exam|null>(null),answersRef=useRef<Record<string,string>>({}),revision=useRef(0),ack=useRef('{}'),saving=useRef<Promise<void>|null>(null),clockOffset=useRef(0),autoSubmitted=useRef(false),blocked=useRef(false);
 function adopt(exam:Exam){paperRef.current=exam;answersRef.current=exam.draft;revision.current=exam.draft_revision;ack.current=JSON.stringify(exam.draft);clockOffset.current=exam.server_now*1000-Date.now();autoSubmitted.current=false;blocked.current=false;setConflict(false);setSync('saved');setPaper(exam);setAnswers(exam.draft);setRemaining(Math.max(0,Math.ceil(exam.deadline-exam.server_now)));setReport(null);}
 async function catalog(id:string){const data=await education<{courses:Course[];specs:Record<string,[number,number]>}>(`assessments/catalog?learner_id=${encodeURIComponent(id)}`);setCourses(data.courses);setSpecs(data.specs);setCourse(data.courses.find(c=>c.grade===c.learning_grade)?.course_version_id||data.courses[0]?.course_version_id||'');}
 useEffect(()=>{let live=true;(async()=>{try{const who=await education<{signed_in_profile_id:string}>('people');if(!who.signed_in_profile_id)throw new Error(t('学习档案尚未关联，请联系家长。'));if(!live)return;setLearner(who.signed_in_profile_id);await catalog(who.signed_in_profile_id);const active=await education<{exam:Exam|null;legacy_task:{set_id:string;learner_id:string;course_version_id:string}|null}>(`assessments/active?learner_id=${encodeURIComponent(who.signed_in_profile_id)}`);if(live&&active.exam){adopt(active.exam);if(active.exam.submitted){const restored=await education<Report>('set/recover',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({learner_id:active.exam.learner_id,course_version_id:active.exam.course_version_id,set_id:active.exam.set_id})});if(live)setReport(restored);}}else if(live&&active.legacy_task)setLegacy(active.legacy_task);}catch(e){if(live)setError((e as Error).message);}finally{if(live)setBusy(false);}})();return()=>{live=false;};},[]);
 const selected=courses.find(c=>c.course_version_id===course);
 useEffect(()=>{setUnit(selected?.units[0]?.id||'');setMode(selected&&selected.learning_grade!==selected.grade?'promotion':'daily');},[course,selected?.learning_grade]);
 const flush=useCallback(async()=>{
  if(saving.current)return saving.current;
  const operation=(async()=>{const current=paperRef.current;if(!current||current.submitted||blocked.current)return;
   while(ack.current!==JSON.stringify(answersRef.current)&&current===paperRef.current){
    if(Date.now()+clockOffset.current>=current.deadline*1000)return;
    const data={...answersRef.current};setSync('saving');
    try{const response=await education<{revision:number}>(`assessments/${current.set_id}/draft`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({answers:data,revision:revision.current})});revision.current=response.revision;ack.current=JSON.stringify(data);setSync('saved');}
    catch(e){blocked.current=true;setConflict(true);setSync('error');setError((e as Error).message);throw e;}
   }
  })();saving.current=operation;try{await operation;}finally{saving.current=null;}
 },[]);
 useEffect(()=>{if(!paper||paper.submitted||report)return;const timer=setTimeout(()=>{void flush().catch(()=>{});},550);return()=>clearTimeout(timer);},[answers,paper,report,flush]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(ack.current!==JSON.stringify(answersRef.current)&&paperRef.current&&!paperRef.current.submitted){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[]);
 async function issue(){setBusy(true);setError('');try{const exam=await education<Exam>('assessments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({learner_id:learner,course_version_id:course,kind:mode,unit_id:mode==='unit'?unit:null})});adopt(exam);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function submit(){const current=paperRef.current;if(!current||busy||blocked.current)return;setBusy(true);setError('');try{
  if(!current.submitted)await flush();
  const data=await education<Report>(current.submitted?'set/recover':'set/submit',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({learner_id:current.learner_id,course_version_id:current.course_version_id,set_id:current.set_id,...(!current.submitted?{answers:current.items.map(i=>({item_id:i.id,response:answersRef.current[i.id]||''}))}:{})})});current.submitted=true;setPaper({...current});setReport(data);setSync('saved');
 }catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const submitRef=useRef(submit);submitRef.current=submit;
 useEffect(()=>{if(!paper||paper.submitted||report)return;const update=()=>{const left=Math.max(0,Math.ceil(paper.deadline-(Date.now()+clockOffset.current)/1000));setRemaining(left);if(left===0&&!autoSubmitted.current&&!blocked.current&&!busy){autoSubmitted.current=true;void submitRef.current();}};update();const timer=setInterval(update,1000);return()=>clearInterval(timer);},[paper,report,busy]);
 async function reload(){if(!paper)return;setBusy(true);setError('');try{adopt(await education<Exam>(`assessments/${paper.set_id}`));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function foundationChoice(choice:'yes'|'no'){
  if(!paper)return;setBusy(true);setError('');
  try{const response=await education<{exam:Exam|null;foundation_followup:FoundationFollowup}>(`assessments/${paper.set_id}/foundation-choice`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({choice})});
   if(response.exam)adopt(response.exam);else setReport(old=>old?{...old,assessment:{...old.assessment,foundation_followup:response.foundation_followup}}:old);
  }catch(e){setError((e as Error).message);}finally{setBusy(false);}
 }
 async function returnToMenu(){setBusy(true);setError('');try{await catalog(learner);paperRef.current=null;setPaper(null);setReport(null);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{viewport.current?.scrollTo(0,0);},[report,paper?.set_id]);
 const choices=(value:unknown)=>Array.isArray(value)?value.map((v,i)=>({label:String(v.label??i+1),text:String(v.text??v)})):Object.entries((value||{}) as Record<string,unknown>).map(([label,text])=>({label,text:String(text)}));
 if(legacy)return <LegacyAssessment task={legacy} onComplete={()=>{void returnToMenu().then(()=>setLegacy(null));}}/>;
 return <div ref={viewport} className="h-full overflow-y-auto"><main className="mx-auto max-w-3xl px-5 py-8 md:px-10 md:py-12"><header className="mb-8"><p className="text-sm text-[var(--primary)]">{t('给理解留下一点证据')}</p><h1 className="mt-2 text-3xl font-semibold">Quiz</h1><p className="mt-3 text-sm leading-7 text-[var(--muted-foreground)]">{t('独立完成测试，提交后查看答案。讲解与订正会自动进入 Chat。')}</p></header>
 {error&&<div role="alert" className="mb-5 rounded-xl border border-red-300 p-4 text-sm text-red-700">{error}{conflict&&<button onClick={reload} disabled={busy} className="ml-3 underline">{t('重新载入已保存作答')}</button>}</div>}
 {!paper&&<section className="space-y-6"><label className="block text-sm font-medium">{t('测试科目')}<select value={course} disabled={busy} onChange={e=>setCourse(e.target.value)} className="mt-2 w-full border p-3">{courses.map(c=><option key={c.course_version_id} value={c.course_version_id}>{c.title} · {t('{{grade}} 年级',{grade:c.grade})}</option>)}</select></label>
 {selected&&<>{selected.learning_grade&&selected.grade<selected.learning_grade?<p role="status" className="rounded-xl bg-[var(--secondary)] p-4 text-sm">{t('对应年级课程尚待发布或分配。')}</p>:null}<p className="text-sm text-[var(--muted-foreground)]">{selected.learning_grade?t('当前学科学习年级：{{grade}}',{grade:selected.learning_grade}):t('请家长先设置这门学科的学习起点。')}</p>{(!selected.learning_grade||selected.grade>=selected.learning_grade)&&<><label className="block text-sm font-medium">{t('测试方式')}<select value={mode} disabled={busy} onChange={e=>setMode(e.target.value)} className="mt-2 w-full border p-3">{selected.modes.filter(m=>!selected.learning_grade||selected.grade===selected.learning_grade||(selected.grade>selected.learning_grade&&m==='promotion')).map(m=><option key={m} value={m}>{names[m as keyof typeof names]}</option>)}</select></label>
 {mode==='unit'&&<label className="block text-sm font-medium">{t('本次单元')}<select value={unit} onChange={e=>setUnit(e.target.value)} className="mt-2 w-full border p-3">{selected.units.map(u=><option key={u.id} value={u.id}>{u.title}{selected.coverage.missing_units.includes(u.id)?'':' ✓'}</option>)}</select></label>}
 <div className="rounded-2xl bg-[var(--secondary)] p-5"><p className="font-medium">{t('{{count}} 题 · {{minutes}} 分钟',{count:specs[mode]?.[0],minutes:specs[mode]?.[1]})}</p><p className="mt-2 text-sm leading-7">{mode==='competition'?t('竞赛只面向 STEM，数学优先。全部为难题；70分达标后，本学科自动升一个年级。之后可选择基础补测。'):mode==='promotion'?t('达到90分并覆盖基础知识后，由家长确认本学科晋级。'):mode==='final'?t('先通过全部单元测试，再通过期末测试；基础知识达标后，本学科自动升一个年级。'):t('提交后统一给出结果；未通过时，先到 Chat 订正，再领取新卷。')}</p><p className="mt-2 text-xs leading-6">{t('开始后持续计时。刷新可恢复已保存作答，超时只接收限时内保存的内容。')}</p></div></>}</>}
 {!busy&&!courses.length&&<p className="rounded-xl bg-[var(--secondary)] p-5 text-sm leading-7">{t('正式题库尚未准备好，请联系家长。Chat 学习仍可继续。')}</p>}
 <button className={primary} disabled={busy||!selected?.learning_grade||selected.grade<selected.learning_grade} onClick={issue}>{busy?t('正在准备…'):t('开始测试')}</button></section>}
 {paper&&!report&&<><div className="sticky top-0 z-10 mb-6 flex flex-wrap items-center justify-between gap-3 rounded-xl border border-[var(--border)] bg-[var(--background)] p-4 text-sm"><span>{names[paper.kind as keyof typeof names]} · {paper.items.length} {t('题')}</span><span className="inline-flex items-center gap-2 tabular-nums"><Clock3 size={16}/>{Math.floor(remaining/60)}:{String(remaining%60).padStart(2,'0')}</span><span role="status" className="text-xs">{sync==='saving'?t('正在保存作答…'):sync==='error'?t('作答尚未保存'):t('作答已保存')}</span></div>
 {paper.submitted?<button disabled={busy} onClick={submit} className={primary}>{t('恢复结果')}</button>:<form className="space-y-8" onSubmit={e=>{e.preventDefault();void submit();}}>{paper.items.map((item,index)=><fieldset key={item.id} disabled={busy||remaining<=0||conflict} className="border-b border-[var(--border)] pb-8"><legend className="mb-3 text-sm font-semibold">{t('第 {{value0}} 题',{value0:index+1})} <span className="ml-3 font-normal text-[var(--muted-foreground)]">{item.points} {t('分')}</span></legend><MarkdownRenderer content={item.prompt}/>{item.figure_url&&<img src={item.figure_url} alt={t('题目配图')} className="my-4 max-h-72 max-w-full"/>}{item.choices!=null&&<div className="my-4 space-y-2">{choices(item.choices).map(c=><label key={c.label} className="flex items-start gap-3 rounded-xl bg-[var(--secondary)] p-3 text-sm"><input type="radio" name={item.id} value={c.label} checked={answers[item.id]===c.label} onChange={()=>{const next={...answersRef.current,[item.id]:c.label};answersRef.current=next;setAnswers(next);setSync('saving');}}/><span>{c.label}. {c.text}</span></label>)}</div>}<label htmlFor={'answer-'+index} className="mb-2 mt-5 block text-sm">{t('你的作答')}</label><textarea id={'answer-'+index} value={answers[item.id]||''} maxLength={20000} onChange={e=>{const next={...answersRef.current,[item.id]:e.target.value};answersRef.current=next;setAnswers(next);setSync('saving');}} rows={3} className="w-full border p-3 text-sm focus:outline-[var(--primary)]"/></fieldset>)}<p className="text-sm text-[var(--muted-foreground)]">{t('未作答的题目按空白提交。')}</p><button disabled={busy||conflict} className={primary}>{busy?t('正在保存和批改…'):t('提交全部作答')}</button></form>}</>}
 {report&&<section><div className="rounded-2xl bg-[var(--secondary)] p-6"><h2 className="text-xl font-semibold">{t('测试结果')}</h2><p className="mt-3 text-3xl font-semibold tabular-nums">{report.assessment.percent??'—'} <span className="text-sm font-normal">/ 100</span></p><p className="mt-3 text-sm leading-7">{paper?.kind==='competition'?report.assessment.passed?t('竞赛通过'):t('竞赛尚未达标'):report.assessment.band==='below_C'?t('尚未及格'):report.assessment.band} · {promotionText(report.assessment)}</p></div>
 {report.assessment.foundation_followup&&<aside aria-label={t('基础知识补测')} className="mt-5 rounded-2xl border border-[var(--border)] bg-[var(--card)] p-6"><h3 className="text-lg font-semibold">{report.assessment.foundation_followup.status==='offered'?t('是否补测基础知识？'):t('基础知识补测')}</h3><p className="mt-3 text-sm leading-7 text-[var(--muted-foreground)]">{report.assessment.foundation_followup.status==='offered'?t('已完成本学科晋级。补测覆盖晋级前年级的核心知识，35题、90分钟，帮助导师安排后续补弱，不影响本次晋级。'):foundationText(report.assessment.foundation_followup)}</p>{report.assessment.foundation_followup.status==='offered'&&<div className="mt-5 flex flex-wrap gap-3"><button disabled={busy} onClick={()=>foundationChoice('yes')} className={primary}>{t('是，开始基础补测')}</button><button disabled={busy} onClick={()=>foundationChoice('no')} className="rounded-xl border border-[var(--border)] px-5 py-3 text-sm">{t('否，结束本轮')}</button></div>}{report.assessment.foundation_followup.status==='in_progress'&&<button disabled={busy} onClick={()=>foundationChoice('yes')} className={primary}>{t('继续基础补测')}</button>}</aside>}
 <div className="my-6 flex flex-wrap gap-3">{report.chat_handoff&&<Link className={primary} href={report.chat_handoff.href}>{t('在 Chat 查看讲解')}</Link>}<button disabled={busy} onClick={returnToMenu} className="rounded-xl border border-[var(--border)] px-5 py-3 text-sm">{t('返回 Quiz')}</button></div><div className="space-y-5">{report.results.map((r,i)=><article key={r.item_id} className="border-b border-[var(--border)] pb-5"><h3 className="mb-2 flex items-center gap-2 font-medium">{r.is_correct&&<Check size={17}/>} {t('第 {{value0}} 题',{value0:i+1})} · {r.is_correct===null?t('等待复核'):r.is_correct?t('正确'):t('需要订正')}</h3><MarkdownRenderer content={r.prompt}/><p className="mt-3 whitespace-pre-wrap text-sm">{t('你的作答：')}{r.your_response||'—'}</p><p className="mt-2 text-sm">{t('参考答案：')}{r.correct_answer}</p></article>)}</div></section>}
 </main></div>;
}
